name = "mealio-ai-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
OPENROUTER_MODEL = "inclusionai/ling-3.0-flash-vl:free"
FRONTEND_ORIGIN = "https://mealio.ishimweshiza324.workers.dev"
